import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/system";
import React from "react";
import Footer from "./Footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const footerSites = [
		{
			text: "Impressum",
			href: "/impressum",
		},
		{
			text: "Datenschutz",
			href: "/datenschutz",
		},
	];

	return (
		<html>
			<body className="bg-background text-foreground antialiased">
				<NextUIProvider>
					<div className="flex min-h-screen flex-col p-4">
						<header>
							<h1 className="text-center font-display-headline text-8xl">
								Volunteer Scheduler
							</h1>
						</header>
						<main className="flex min-h-full flex-1 flex-col">{children}</main>
						<footer className="flex h-4 justify-center gap-4">
							<Footer sites={footerSites} />
						</footer>
					</div>
				</NextUIProvider>
			</body>
		</html>
	);
}
