import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/system";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html>
			<body className="bg-background text-foreground antialiased">
				<NextUIProvider>
					<div className="flex min-h-screen flex-col p-4">
						<header>
							<h1 className="text-center font-display-headline text-8xl">
								Volunteer Scheduler
							</h1>
						</header>
						<main className="flex min-h-full flex-1 flex-col">{children}</main>
					</div>
				</NextUIProvider>
			</body>
		</html>
	);
}
